/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Utilidades.AbrirFormulario;
import vista.frmProductos;
import vista.frmClientes;
import vista.frmProveedores;
import vista.frmVentas;
import vista.frmHistorialVentas;
import vista.frmInventario;
import vista.frmFacturacion;

public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucatalogo = new javax.swing.JMenu();
        itemProductos = new javax.swing.JMenuItem();
        itemClientes = new javax.swing.JMenuItem();
        itemProveedores = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        itemRealizarVenta = new javax.swing.JMenuItem();
        itemConsultarVentas = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        itemInventario = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        itemFacturacion = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        menucatalogo.setText("Catalogo");

        itemProductos.setText("productos");
        itemProductos.addActionListener(this::itemProductosActionPerformed);
        menucatalogo.add(itemProductos);

        itemClientes.setText("Clientes");
        itemClientes.addActionListener(this::itemClientesActionPerformed);
        menucatalogo.add(itemClientes);

        itemProveedores.setText("Proveedores");
        itemProveedores.addActionListener(this::itemProveedoresActionPerformed);
        menucatalogo.add(itemProveedores);

        jMenuBar1.add(menucatalogo);

        menuVentas.setText("Ventas");

        itemRealizarVenta.setText("Realizar venta");
        itemRealizarVenta.addActionListener(this::itemRealizarVentaActionPerformed);
        menuVentas.add(itemRealizarVenta);

        itemConsultarVentas.setText("Consultar ventas");
        itemConsultarVentas.addActionListener(this::itemConsultarVentasActionPerformed);
        menuVentas.add(itemConsultarVentas);

        jMenuBar1.add(menuVentas);

        menuInventario.setText("Inventario");

        itemInventario.setText("Inventario");
        itemInventario.addActionListener(this::itemInventarioActionPerformed);
        menuInventario.add(itemInventario);

        jMenuBar1.add(menuInventario);

        menuSistema.setText("Sistema");

        itemFacturacion.setText("facturacion");
        itemFacturacion.addActionListener(this::itemFacturacionActionPerformed);
        menuSistema.add(itemFacturacion);

        itemSalir.setText("salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuSistema.add(itemSalir);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        frmClientes frm = new frmClientes();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        frmProductos frm = new frmProductos();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedoresActionPerformed
        frmProveedores frm = new frmProveedores();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemProveedoresActionPerformed

    private void itemRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRealizarVentaActionPerformed
      frmVentas frm = new frmVentas();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemRealizarVentaActionPerformed

    private void itemConsultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarVentasActionPerformed
     frmHistorialVentas frm = new frmHistorialVentas();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemConsultarVentasActionPerformed

    private void itemFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFacturacionActionPerformed
       frmFacturacion frm = new frmFacturacion();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemFacturacionActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Desea salir del sistema?",
        "Salir",
        javax.swing.JOptionPane.YES_NO_OPTION);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {

    System.exit(0);

}
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInventarioActionPerformed
        frmInventario frm = new frmInventario();

AbrirFormulario.abrir(desktopPane, frm);
    }//GEN-LAST:event_itemInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemConsultarVentas;
    private javax.swing.JMenuItem itemFacturacion;
    private javax.swing.JMenuItem itemInventario;
    private javax.swing.JMenuItem itemProductos;
    private javax.swing.JMenuItem itemProveedores;
    private javax.swing.JMenuItem itemRealizarVenta;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenu menucatalogo;
    // End of variables declaration//GEN-END:variables
}
