/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import Controlador.clienteController;
import Controlador.ProductoController;
import Controlador.ventaController;
import Modelo.Cliente;
import Modelo.DetalleVenta;
import Modelo.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class frmVentas extends javax.swing.JInternalFrame {

private clienteController clienteController;
private ProductoController productoController;
private ventaController ventaController;

private List<Cliente> clientes;
private List<Producto> productos;

private double total = 0;

   public frmVentas() {

    initComponents();

    clienteController = new clienteController();
    productoController = new ProductoController();
    ventaController = new ventaController();

    txtPrecio.setEnabled(false);
    txtSubtotal.setEnabled(false);
    txtTotal.setEnabled(false);

    txtCantidad.setText("1");
    txtPrecio.setText("0.00");
    txtSubtotal.setText("0.00");
    txtTotal.setText("0.00");

    cargarClientes();
    cargarProductos();
}
   private void cargarClientes() {

    cmbCliente.removeAllItems();

    clientes = clienteController.listarClientes();

    for (Cliente cliente : clientes) {

        cmbCliente.addItem(
                cliente.getIdCliente()
                + " - "
                + cliente.getNombre()
        );
    }
}
   private void cargarProductos() {

    cmbProducto.removeAllItems();

    productos = productoController.listarProductos();

    for (Producto producto : productos) {

        cmbProducto.addItem(
                producto.getIdProducto()
                + " - "
                + producto.getNombre()
        );
    }
}
   private Producto obtenerProductoSeleccionado() {

    int indice = cmbProducto.getSelectedIndex();

    if (indice < 0 || productos == null
            || indice >= productos.size()) {

        return null;
    }

    return productos.get(indice);
}
   private void calcularSubtotal() {

    Producto producto = obtenerProductoSeleccionado();

    if (producto == null) {
        return;
    }

    try {

        int cantidad = Integer.parseInt(
                txtCantidad.getText().trim()
        );

        if (cantidad <= 0) {
            txtSubtotal.setText("0.00");
            return;
        }

        double precio = producto.getPrecio();

        double subtotal = cantidad * precio;

        txtSubtotal.setText(
                String.format("%.2f", subtotal)
        );

    } catch (NumberFormatException e) {

        txtSubtotal.setText("0.00");
    }
}
   private void limpiarVenta() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblDetalle.getModel();

    modelo.setRowCount(0);

    total = 0;

    txtCantidad.setText("1");
    txtPrecio.setText("0.00");
    txtSubtotal.setText("0.00");
    txtTotal.setText("0.00");

    if (cmbCliente.getItemCount() > 0) {
        cmbCliente.setSelectedIndex(0);
    }

    if (cmbProducto.getItemCount() > 0) {
        cmbProducto.setSelectedIndex(0);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Ventas");

        jLabel2.setText("Cliente:");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Producto:");

        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProducto.addActionListener(this::cmbProductoActionPerformed);

        jLabel4.setText("Cantidad");

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });

        jLabel5.setText("Precio");

        txtPrecio.setEnabled(false);

        jLabel6.setText("SubTotal");

        txtSubtotal.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        jLabel7.setText("Total");

        txtTotal.setEnabled(false);

        btnRegistrar.setText("Registrar Venta");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel8.setText("\"Es necesario lipiar antes de comenzar\"");

        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(cmbCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(cmbProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtSubtotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnRegistrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(26, 26, 26)
                        .addComponent(btnRegistrar)
                        .addGap(23, 23, 23))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(txtTotal)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8)
                                .addGap(93, 93, 93))))))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jDesktopPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
   int idCliente = obtenerIdClienteSeleccionado();

    if (idCliente == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un cliente."
        );

        return;
    }

    DefaultTableModel modelo =
            (DefaultTableModel) tblDetalle.getModel();

    if (modelo.getRowCount() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Agregue al menos un producto."
        );

        return;
    }

    List<DetalleVenta> detalles =
            new ArrayList<>();

    for (int i = 0; i < modelo.getRowCount(); i++) {

        int idProducto = Integer.parseInt(
                modelo.getValueAt(i, 0).toString()
        );

        int cantidad = Integer.parseInt(
                modelo.getValueAt(i, 2).toString()
        );

        double precio = Double.parseDouble(
                modelo.getValueAt(i, 3).toString()
        );

        double subtotal = Double.parseDouble(
                modelo.getValueAt(i, 4).toString()
        );

        DetalleVenta detalle =
                new DetalleVenta();

        detalle.setIdProducto(idProducto);
        detalle.setCantidad(cantidad);
        detalle.setPrecio(precio);
        detalle.setSubtotal(subtotal);

        detalles.add(detalle);
    }

    boolean resultado =
            ventaController.registrarVenta(
                    idCliente,
                    total,
                    detalles
            );

    if (resultado) {

        JOptionPane.showMessageDialog(
                this,
                "Venta registrada correctamente."
        );

        limpiarVenta();

        cargarProductos();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar la venta.\n"
                + "Verifique la existencia de los productos."
        );
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
       Producto producto = obtenerProductoSeleccionado();

    if (producto != null) {

        txtPrecio.setText(
                String.format("%.2f", producto.getPrecio())
        );

        calcularSubtotal();
    }
    }//GEN-LAST:event_cmbProductoActionPerformed
private void calcularTotal() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblDetalle.getModel();

    total = 0;

    for (int i = 0; i < modelo.getRowCount(); i++) {

        double subtotal = Double.parseDouble(
                modelo.getValueAt(i, 4).toString()
        );

        total += subtotal;
    }

    txtTotal.setText(
            String.format("%.2f", total)
    );
}
private int obtenerIdClienteSeleccionado() {

    int indice = cmbCliente.getSelectedIndex();

    if (indice < 0 || clientes == null
            || indice >= clientes.size()) {

        return -1;
    }

    return clientes.get(indice).getIdCliente();
}
    
    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
      calcularSubtotal();
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         Producto producto = obtenerProductoSeleccionado();

    if (producto == null) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto."
        );

        return;
    }

    int cantidad;

    try {

        cantidad = Integer.parseInt(
                txtCantidad.getText().trim()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Ingrese una cantidad válida."
        );

        return;
    }

    if (cantidad <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "La cantidad debe ser mayor que cero."
        );

        return;
    }

    if (cantidad > producto.getExistencia()) {

        JOptionPane.showMessageDialog(
                this,
                "No hay suficiente existencia.\n"
                + "Existencia disponible: "
                + producto.getExistencia()
        );

        return;
    }

    double precio = producto.getPrecio();

    double subtotal = cantidad * precio;

    DefaultTableModel modelo =
            (DefaultTableModel) tblDetalle.getModel();

    // Verificar si el producto ya está agregado
    for (int i = 0; i < modelo.getRowCount(); i++) {

        int idExistente = Integer.parseInt(
                modelo.getValueAt(i, 0).toString()
        );

        if (idExistente == producto.getIdProducto()) {

            JOptionPane.showMessageDialog(
                    this,
                    "El producto ya está agregado a la venta."
            );

            return;
        }
    }

    modelo.addRow(new Object[]{
        producto.getIdProducto(),
        producto.getNombre(),
        cantidad,
        precio,
        subtotal
    });

    calcularTotal();

    txtCantidad.setText("1");
    txtSubtotal.setText("0.00");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int fila = tblDetalle.getSelectedRow();

    if (fila < 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto de la venta."
        );

        return;
    }

    DefaultTableModel modelo =
            (DefaultTableModel) tblDetalle.getModel();

    modelo.removeRow(fila);

    calcularTotal();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
          limpiarVenta();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
